const JavaScriptVideos = [
  {
    id: 1,
    url: "https://www.youtube.com/watch?v=_ApRMRGI-6g",
    image: "http://img.youtube.com/vi/_ApRMRGI-6g/mqdefault.jpg",
    title: "Heres how JavaScript's Nested Object Destructuring works",
    path: "/courses/javascript/1",
    completed: false,
  },
  {
    id: 2,
    url: "https://www.youtube.com/watch?v=NIq3qLaHCIs&t=374s",
    image: "http://img.youtube.com/vi/NIq3qLaHCIs/mqdefault.jpg",
    title: "Why Is Array/Object Destructuring So Useful And How To Use It",
    path: "/courses/javascript/2",
    completed: false,
  },
  {
    id: 3,
    url: "https://www.youtube.com/watch?v=-vR3a11Wzt0",
    image: "http://img.youtube.com/vi/-vR3a11Wzt0/mqdefault.jpg",
    title: "Destructuring in ES6 - Beau teaches JavaScript",
    path: "/courses/javascript/3",
    completed: false,
  },
  {
    id: 4,
    url: "https://www.youtube.com/watch?v=iLx4ma8ZqvQ&t=193s",
    image: "http://img.youtube.com/vi/iLx4ma8ZqvQ/mqdefault.jpg",
    title: "...spread operator and rest operator - Beau teaches JavaScript",
    path: "/courses/javascript/4",
    completed: false,
  },
  {
    id: 5,
    url: "https://www.youtube.com/watch?v=V_Kr9OSfDeU",
    image: "http://img.youtube.com/vi/V_Kr9OSfDeU/mqdefault.jpg",
    title: "JavaScript Async Await",
    path: "/courses/javascript/5",
    completed: false,
  },
  {
    id: 6,
    url: "https://www.youtube.com/watch?v=Bv_5Zv5c-Ts",
    image: "http://img.youtube.com/vi/Bv_5Zv5c-Ts/mqdefault.jpg",
    title: "JavaScript: Understanding the Weird Parts - The First 3.5 Hours",
    path: "/courses/javascript/6",
    completed: false,
  },
];
