const TypeScriptVideos = [
  {
    id: 1,
    url: "https://www.youtube.com/watch?v=zQnBQ4tB3ZA",
    image: "http://img.youtube.com/vi/zQnBQ4tB3ZA/mqdefault.jpg",
    title: "TypeScript in 100 Seconds",
    path: "/courses/typescript/1",
    completed: false,
  },
  {
    id: 2,
    url: "https://www.youtube.com/watch?v=BwuLxPH8IDs&t=3341s",
    image: "http://img.youtube.com/vi/BwuLxPH8IDs/mqdefault.jpg",
    title:
      "TypeScript Course for Beginners 2020 - Learn TypeScript from Scratch!",
    path: "/courses/typescript/2",
    completed: false,
  },
  {
    id: 3,
    url: "https://www.youtube.com/watch?v=WBPrJSw7yQA&t=1397s",
    image: "http://img.youtube.com/vi/WBPrJSw7yQA/mqdefault.jpg",
    title: "Learn TypeScript in 50 Minutes - Tutorial for Beginners",
    path: "/courses/typescript/3",
    completed: false,
  },
  {
    id: 4,
    url: "https://www.youtube.com/watch?v=1UcLoOD1lRM&t=282s",
    image: "http://img.youtube.com/vi/1UcLoOD1lRM/mqdefault.jpg",
    title: "Using Typescript in Node.js",
    path: "/courses/typescript/4",
    completed: false,
  },
  {
    id: 5,
    url: "https://www.youtube.com/watch?v=Z5iWr6Srsj8&t=1204s",
    image: "http://img.youtube.com/vi/Z5iWr6Srsj8/mqdefault.jpg",
    title: "React Typescript Tutorial",
    path: "/courses/typescript/5",
    completed: false,
  },
  {
    id: 6,
    url: "https://www.youtube.com/watch?v=F2JCjVSZlG0&t=3204s",
    image: "http://img.youtube.com/vi/F2JCjVSZlG0/mqdefault.jpg",
    title: "React / Typescript Tutorial - Build a Quiz App",
    path: "/courses/typescript/6",
    completed: false,
  },
];
